modLoader = 'javafml'
loaderVersion = '[40,)'
license = 'LGPL-3.0-only'
logoFile = 'assets/hoofprint/icon.png'

[properties]
"connector:placeholder"=true

[[mods]]
modId = 'hoofprint'
version = '${version}'
displayName = 'Hoofprint'
description = 'A barebones surveyor-powered minecraft world map.'
authors = 'Garden System'
displayURL = 'https://modrinth.com/mod/hoofprint'

[[dependencies.hoofprint]]
modId = "minecraft"
mandatory = true
versionRange = "[${mc},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hoofprint]]
modId = "connectormod"
mandatory = true
versionRange = "*"


[[dependencies.hoofprint]]
modId = "fabric_api"
mandatory = true
versionRange = "[${fapi},)"
